-- MySQL Script generated by MySQL Workbench
-- sáb 11 jul 2015 00:34:52 CDT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bibroSecurity
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bibroSecurity` ;
CREATE SCHEMA IF NOT EXISTS `bibroSecurity` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `bibroSecurity` ;

-- -----------------------------------------------------
-- Table `partner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `partner` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `partner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `lastName` VARCHAR(60) NOT NULL,
  `street` VARCHAR(45) NULL,
  `noExt` VARCHAR(45) NULL,
  `noInt` VARCHAR(45) NULL,
  `colony` VARCHAR(45) NULL,
  `zip` VARCHAR(10) NULL,
  `locality` VARCHAR(60) NULL,
  `phone` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `customer` TINYINT(1) NULL DEFAULT 1,
  `supplier` TINYINT(1) NULL DEFAULT 0,
  `image` VARCHAR(1000) NULL,
  `city_id` INT NULL,
  `state_id` INT NULL,
  `country_id` INT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `userType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userType` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `userType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `partner_id` INT NULL,
  `active` TINYINT(1)  NOT NULL DEFAULT 1,
  `userType_id` INT NOT NULL DEFAULT 2,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `parent_id` INT NULL,
  `full_name` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `purchasePrice` DOUBLE NOT NULL DEFAULT 0.0,
  `salePrice` DOUBLE NOT NULL DEFAULT 0.0,
  `qtyAvailable` DOUBLE NOT NULL DEFAULT 0.0,
  `incomingQty` DOUBLE NOT NULL DEFAULT 0.0,
  `virtualAvailable` DOUBLE NOT NULL DEFAULT 0.0,
  `ean13` VARCHAR(45) NULL,
  `uom` VARCHAR(45) NOT NULL,
  `category_id` INT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `partner_id` INT NOT NULL,
  `image` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `saleOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `saleOrder` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `saleOrder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime_create` DATETIME NULL,
  `subTotal` DOUBLE NOT NULL DEFAULT 0.0,
  `discount` DOUBLE NOT NULL DEFAULT 0.0,
  `total` DOUBLE NOT NULL DEFAULT 0.0 COMMENT '	',
  `type` ENUM('saleorder','invoice') NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'confirmed',
  `partner_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `purchaseOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `purchaseOrder` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `purchaseOrder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime_create` DATETIME NULL,
  `subtotal` DOUBLE NOT NULL,
  `total` DOUBLE NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT 'draft',
  `partner_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `saleOrderLine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `saleOrderLine` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `saleOrderLine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saleOrder_id` INT NOT NULL,
  `qty` DOUBLE NULL,
  `unit_price` DOUBLE NULL,
  `subtotal` DOUBLE NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `purchaseOrderLine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `purchaseOrderLine` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `purchaseOrderLine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qty` DOUBLE NULL,
  `unit_price` DOUBLE NULL,
  `subtotal` DOUBLE NULL,
  `product_id` INT NOT NULL,
  `purchaseOrder_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `service` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(100) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `partner_id` INT NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `camera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `camera` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `camera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(100) NOT NULL,
  `ipv4` VARCHAR(45) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `multimedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `multimedia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `multimedia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(1000) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `productImage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productImage` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `productImage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `image` VARCHAR(1000) NOT NULL,
  `description` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `serviceCamera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceCamera` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `serviceCamera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_id` INT NOT NULL,
  `camera_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `package` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `package` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `partner_id` INT NOT NULL,
  `active` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `saleOrderPackage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `saleOrderPackage` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `saleOrderPackage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `package_id` INT NOT NULL,
  `saleOrder_id` INT NOT NULL,
  `guide_number` VARCHAR(100) NULL,
  `sending_date` DATE NOT NULL,
  `arrival_date` DATE NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;



-- -----------------------------------------------------
-- Data for table `userType`
-- -----------------------------------------------------
START TRANSACTION;
USE `bibroSecurity`;
INSERT INTO `userType` (`id`, `name`, `active`) VALUES (1, 'Administrador', 1);
INSERT INTO `userType` (`id`, `name`, `active`) VALUES (2, 'Usuario', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`
-- -----------------------------------------------------
START TRANSACTION;
USE `bibroSecurity`;
INSERT INTO `user` (`id`, `name`, `lastName`, `email`, `password`,  `active`, `userType_id`) VALUES (1, 'Administrador', 'Administrador', 'admin@admin.com', 'admin', 1, 1);

COMMIT;




delimiter //
CREATE TRIGGER utrg_UpdateQtyAvalible AFTER INSERT ON saleOrderLine
FOR EACH ROW
BEGIN
	UPDATE product SET qtyAvailable = qtyAvailable - NEW.qty,virtualAvailable = virtualAvailable - NEW.qty 
	WHERE id = NEW.product_id;
END//


-- delimiter //
-- CREATE TRIGGER  Usuario_usertype AFTER INSERT ON user
-- 	FOR EACH ROW
-- 	BEGIN
-- 	UPDATE user SET userType_id=2 where id=new.id;
-- END//

-- delimiter //
-- CREATE TRIGGER  Usuario_partner AFTER INSERT ON user
-- 	FOR EACH ROW
-- 	BEGIN
-- 	insert into partner(name,lastName,email,customer) values (new.name, new.lastName, new.email, true);
-- 	set @id= (select max(id) from partner);
-- 	UPDATE user SET partner_id=@id where id=new.id;
-- END//

delimiter ;


-- -----------------------------------------------------
-- Data for table `product`
-- -----------------------------------------------------
START TRANSACTION;
USE `bibroSecurity`;
INSERT INTO `product` (`id`, `name`, `description`, `purchasePrice`, `salePrice`, `qtyAvailable`, `incomingQty`, `virtualAvailable`, `ean13`, `uom`, `category_id`, `active`, `partner_id`, `image`) VALUES (1, 'Camara IP PTZ', 'Camara IP PTZ', 8500, 10800, 5, 3, 8, 'E918', 'ptz', 1, 1, 3, 'image1.png');
INSERT INTO `product` (`id`, `name`, `description`, `purchasePrice`, `salePrice`, `qtyAvailable`, `incomingQty`, `virtualAvailable`, `ean13`, `uom`, `category_id`, `active`, `partner_id`, `image`) VALUES (2, 'DVR- multicanales', 'DVR- multicanales', 3200, 5000, 4, 2, 6, 'E731A', 'ptz', 1, 1, 3, 'image2.png');
INSERT INTO `product` (`id`, `name`, `description`, `purchasePrice`, `salePrice`, `qtyAvailable`, `incomingQty`, `virtualAvailable`, `ean13`, `uom`, `category_id`, `active`, `partner_id`, `image`) VALUES (3, 'DVR- ADHUA', 'Multiple network monitoring: Web viewer, CMS(DSS/Smart PSS)&Smart Phone(DMSS)', 4500, 5500, 3, 2, 5, 'B64R', 'pz', 1, 1, 10, 'image3.png');
INSERT INTO `product` (`id`, `name`, `description`, `purchasePrice`, `salePrice`, `qtyAvailable`, `incomingQty`, `virtualAvailable`, `ean13`, `uom`, `category_id`, `active`, `partner_id`, `image`) VALUES (4, 'DOMO IP PROFESIONAL EPCOM',  'DOMO IP PROFESIONAL EPCOM', 5000, 5800, 3, 2, 5, 'E65RA', 'PZ', 1, 1, 4, 'image4.png');
INSERT INTO `product` (`id`, `name`, `description`, `purchasePrice`, `salePrice`, `qtyAvailable`, `incomingQty`, `virtualAvailable`, `ean13`, `uom`, `category_id`, `active`, `partner_id`, `image`) VALUES (5, 'CAMARA IP TIPO BALA 3MP', 'CAMARA IP TIPO BALA 3MP', 3000, 4000, 4, 3, 7, 'GR44', 'PZ', 1, 1, 5, 'image5.png');
INSERT INTO `product` (`id`, `name`, `description`, `purchasePrice`, `salePrice`, `qtyAvailable`, `incomingQty`, `virtualAvailable`, `ean13`, `uom`, `category_id`, `active`, `partner_id`, `image`) VALUES (6, 'SOPORTE DE CAMARA TIPO BALA', 'SOPORTE DE CAMARA TIPO BALA', 900, 1300, 2, 3, 5, NULL, 'PZ', 1, 1, 2, 'image6.png');
INSERT INTO `product` (`id`, `name`, `description`, `purchasePrice`, `salePrice`, `qtyAvailable`, `incomingQty`, `virtualAvailable`, `ean13`, `uom`, `category_id`, `active`, `partner_id`, `image`) VALUES (7, 'SOPORTE DE CAMARA PTZ', 'SOPORTE DE CAMARA PTZ', 1000, 1500, 3, 2, 5, NULL, 'PZ', 1, 1, 4, 'image7.png');
INSERT INTO `product` (`id`, `name`, `description`, `purchasePrice`, `salePrice`, `qtyAvailable`, `incomingQty`, `virtualAvailable`, `ean13`, `uom`, `category_id`, `active`, `partner_id`, `image`) VALUES (8, 'CONTROL DE ACCESO OPTICO', 'CONTROL DE ACCESO OPTICO', 12000, 18000, 1, 1, 2, 'ERFF45', 'PZ', 1, 1, 4, 'image8.png');
INSERT INTO `product` (`id`, `name`, `description`, `purchasePrice`, `salePrice`, `qtyAvailable`, `incomingQty`, `virtualAvailable`, `ean13`, `uom`, `category_id`, `active`, `partner_id`, `image`) VALUES (9, 'CONTROL DE ACCESO DE HUELLA', 'CONTROL DE ACCESO DE HUELLA', 1450, 20000, 1, 0, 1, 'SSE345', 'PZ', 1, 1, 6, 'image9.png');
INSERT INTO `product` (`id`, `name`, `description`, `purchasePrice`, `salePrice`, `qtyAvailable`, `incomingQty`, `virtualAvailable`, `ean13`, `uom`, `category_id`, `active`, `partner_id`, `image`) VALUES (10, 'CAMARA ADHUA PARA EXTERIORES', 'CAMARA ADHUA PARA EXTERIORES', 6700, 7500, 2, 1, 3, 'EQW3', 'PZ', 1, 1, 10, 'image10.png');

COMMIT;


-- -----------------------------------------------------
-- Data for table `partner`
-- -----------------------------------------------------
START TRANSACTION;
USE `bibroSecurity`;
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'HIKVISION', '', 'Avenida Industrial', '372', NULL, 'Industrial', '87662', 'JALISCO', '2345612', NULL, 'contacto@hikvision.com.mx', 0, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'EPCOM', '', 'Avenida de los Insurgentes', '1504', NULL, 'Insurgentes', '47843', 'D.F', '3456782', NULL, 'ventas@epcom.com.mx', 0, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'IDIS', 'IDIS', 'Avenida de las Lomas', '293', NULL, 'Las Lomas', '34985', 'EDO. MEXICO', '4 566253', NULL, 'Brendalopez@idis.com', 0, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` (`name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'ACTI', 'ACTI', 'Revolucion', '1001', NULL, 'Arcos del Sol', '56719', 'MONTERREY', NULL, NULL, 'ventas@acti.com', 0, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` (`name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'NUUO', 'NUUO', 'Paseo de los Insurgentes', '102', '29', 'Insurgentes', '47923', 'D.F', '3568213', NULL, 'contacto@nuuo.com.mx', 0, 1, '', NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'JVC', 'JVC', 'Lomas de Ginea', '1101', NULL, 'Lomas de Barcelona', '56774', 'MONTERREY', '3425117', NULL, 'contacto@jvc.com.mx', 0, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'BELDEN', 'BELDEN', 'Alcatraz', '2652', NULL, 'Los Romeros', '87252', 'JALISCO', '2366621', NULL, 'gonzalo@belden.com.mx', 0, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'HOCHIKI', 'HOCHIKI', 'Altamirano', '231', NULL, 'Reforma', '56722', 'CUERNAVACA', '2342561', NULL, 'miriam@hochiki.com.mx', 0, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ('HONEYWELL', 'HONEYWELL', 'Plan de Ayala', '554', NULL, 'Mexico', '72622', 'EDO. MEXICO', '4352366', NULL, 'ventas@honeywell.com.mx', 0, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'DAHUA', 'DAHUA', 'Loma Antigua', '314', NULL, 'Las Lomas', '34985', 'EDO. MEXXICO', '3456116', NULL, 'ventas@dahua.com.mx', 0, 1, '', NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'IVAN', 'GOMEZ', 'La martinica', '1322', NULL, 'Lopez Mateos Blvd.', '37889', 'LEON', '3221144', NULL, 'ivang@hotmail.com', 1, 0, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'DANIEL', 'GARCIA', 'Jardinez del moral', '321', NULL, 'Paseos del moral', '78358', 'LEON', '7778821', NULL, 'miss@hotail.com', 1, 0, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'CURTIDOZ DE ALTA CALIDAD', 'algo', 'Burundanga', '1221', NULL, 'El Cohecillo', '37892', 'LEON', '7882173', NULL, 'yuliana@gac.com', 1, 0, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'PATRONATO DE LA FERIA DE LEON Y PARQUE EXPLORA', 'algo', 'La Martinica', '2309', NULL, 'Lopez Mateos Blvd', '37000', 'LEON', '7466098', NULL, 'comunicaciones@ferialeon.org', 1, 0, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'EDUARDO ', 'PEREZ', '5 de Febrero', '4323', NULL, 'Centro', '37000', 'LEON', '7009273', NULL, 'perez9000@outlook.com', 1, 0, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ( 'YESENIA', 'LAZALDE', 'Lomas del Campestre', '767', NULL, 'Campestre', '37090', 'LEON', '7882244', NULL, 'lazalde19@hotmail.com', 1, 0, NULL, NULL, NULL, NULL, 1);
INSERT INTO `partner` ( `name`, `lastName`, `street`, `noExt`, `noInt`, `colony`, `zip`, `locality`, `phone`, `mobile`, `email`, `customer`, `supplier`, `image`, `city_id`, `state_id`, `country_id`, `active`) VALUES ('administrador', 'administrador', NULL, NULL, NULL, NULL, NULL, 'LEON', '7989834', NULL, 'administrador@bibrosecurity.com', 1, 0, NULL, NULL, NULL, NULL, 1);

COMMIT;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
